language: node_js

sudo: false

git:
  depth: 3

node_js:
  - 4
  - 6
  - 8
  - 10
  - 12
  - 14
  - 16

script:
  - npm run-script cover

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
